package cn.rongcloud.im.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table QUN.
 */
public class Groups implements Serializable{

    private static final long serialVersionUID = 2081549829659285694L;
    /** Not-null value. */
    private String qunId;
    private String name;
    private String portraitUri;
    private String displayName;
    private String role;
    private Long timestamp;

    public Groups() {
    }

    public Groups(String qunId) {
        this.qunId = qunId;
    }

    public Groups(String qunId, String name, String portraitUri, String displayName, String role, Long timestamp) {
        this.qunId = qunId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.displayName = displayName;
        this.role = role;
        this.timestamp = timestamp;
    }

    public Groups(String qunId, String name, String portraitUri, String role) {
        this.qunId = qunId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.role = role;
    }


    public Groups(String qunId, String name, String portraitUri) {
        this.qunId = qunId;
        this.name = name;
        this.portraitUri = portraitUri;
    }

    /** Not-null value. */
    public String getQunId() {
        return qunId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setQunId(String qunId) {
        this.qunId = qunId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPortraitUri() {
        return portraitUri;
    }

    public void setPortraitUri(String portraitUri) {
        this.portraitUri = portraitUri;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

}
