package cn.rongcloud.im.server.pinyin;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 


import java.io.Serializable;

/**
 * Entity mapped to table FRIEND.
 */
public class Friend implements Serializable{

    private static final long serialVersionUID = 8270277246566381723L;
    /** Not-null value. */
    private String userId;
    private String name;
    private String portraitUri;
    private String displayName;
    private String status;
    private Long timestamp;
    private String letters;

    public String getLetters() {
        return letters;
    }

    public void setLetters(String letters) {
        this.letters = letters;
    }

    public Friend() {
    }

    public Friend(String userId) {
        this.userId = userId;
    }

    public Friend(String userId,String name,String portraitUri){
        this.userId = userId;
        this.name = name;
        this.portraitUri = portraitUri;
    }


    public Friend(String userId,String name,String portraitUri,String letters){
        this.userId = userId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.letters = letters;
    }

    public Friend(String userId, String name, String portraitUri, String displayName, String status, Long timestamp) {
        this.userId = userId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.displayName = displayName;
        this.status = status;
        this.timestamp = timestamp;
    }

    /** Not-null value. */
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPortraitUri() {
        return portraitUri;
    }

    public void setPortraitUri(String portraitUri) {
        this.portraitUri = portraitUri;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

}
